config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'relationships/create'
  get 'relationships/destroy'
  get "following_posts" => "posts#following_posts"#追記
  get 'bookmarks/create'
  get 'bookmarks/destroy'
  get 'bookmarks/index'
  get 'items/index'
  root "posts#index"
  get '/post/hashtag/:name', to: "posts#hashtag"
  get '/post/:address', to: "posts#map"
  post '/posts/:post_id/favorites' => "favorites#create"
  delete '/posts/:post_id/favorites' => "favorites#destroy"
  
  resources :notifications, only: :index
  resources :categories, only: [:index, :new]

  resources :posts do
    resources :comments, only: [:create, :destroy]
    namespace :api do
      resources :comments, only: :index, defaults: { format: 'json' }
    end
    member do
      get :following, :followers, :users_posts#追記
      get :map
    end
    resource :bookmarks, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    
    collection do
      get 'search'
    end
  end

  
  resources :users do
    resources :notifications, only: :index
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # 追加
    get :followers, on: :member # 追加
    get :bookmarks, on: :member
  end
  

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_post

  def create
    @favorite = Favorite.create(user_id: current_user.id, post_id: params[:post_id])
    @favorites = Favorite.where(post_id: params[:post_id])
    @post.reload
  end

  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, post_id: params[:post_id])
    favorite.destroy
    @favorites = Favorite.where(post_id: params[:post_id])
    @post.reload
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
  
end

app/helpers/favorites_helper.rb
module FavoritesHelper
  def favorite_icon(post, user)
    if user
      if user.favorites.exists?(post: post)
        '<i class="far fa-smile-beam"></i>'
      else
        '<i class="far fa-smile-wink fa-smile-wink-o"></i>'
      end
    end
  end
end

app/views/favorites/_favorite.html.haml
//いいね件数
- if user_signed_in?
  - if current_user.already_favorited?(@post)
    = link_to post_favorites_path(@post), method: :delete, id: 'favorite-link', remote: true do
      = raw favorite_icon(@post, current_user)
      %h6= @post.favorites.count.to_s
  - else
    = link_to post_favorites_path(@post), method: :post, id: 'favorite-link-to', remote: true do
      = raw favorite_icon(@post, current_user)
      %h6= @post.favorites.count.to_s

app/views/favorites/create.js.haml
$('#favorite-link-to').html("#{j(render partial: 'favorite', locals: {post: @post})}");

app/views/favorites/destroy.js.haml
$('#favorite-link').html("#{j(render partial: 'favorite', locals: {post: @post})}");