config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'relationships/create'
  get 'relationships/destroy'
  get "following_posts" => "posts#following_posts"#追記
  get 'bookmarks/create'
  get 'bookmarks/destroy'
  get 'bookmarks/index'
  get 'items/index'
  root "posts#index"
  get '/post/hashtag/:name', to: "posts#hashtag"
  get '/post/:address', to: "posts#map"
  post '/posts/:post_id/favorites' => "favorites#create"
  delete '/posts/:post_id/favorites' => "favorites#destroy"
  
  resources :notifications, only: :index
  resources :categories, only: [:index, :new]

  resources :posts do
    resources :comments, only: [:create, :destroy]
    namespace :api do
      resources :comments, only: :index, defaults: { format: 'json' }
    end
    member do
      get :following, :followers, :users_posts#追記
      get :map
    end
    resource :bookmarks, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    
    collection do
      get 'search'
    end
  end

  
  resources :users do
    resources :notifications, only: :index
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # 追加
    get :followers, on: :member # 追加
    get :bookmarks, on: :member
  end
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments

  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  has_many :bookmarks, dependent: :destroy

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  
  mount_uploader :avatar, AvatarUploader

  validates :name, presence: true, uniqueness: true, length: { maximum: 8 }
  

  def already_favorited?(post)
    self.favorites.exists?(post_id: post.id)
  end

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def bookmarked_by?(user)
    passive_bookmarks.find_by(post_id: user.id).present?
  end

  def create_notification_following!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'following'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'following'
      )
      notification.save if notification.valid?
    end
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
  
  def show
    @parents = Category.all.order("id ASC").limit(2)
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(20).order("created_at DESC")
    @name = @user.name
    @favorite_posts = @user.favorite_posts
    @bookmark_posts = @user.bookmark_ids
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end
  

  def like(post)
    favorites.find_or_create_by(post_id: post.id)
  end

  def unlike(post)
    favorite = favorites.find_by(post_id: post.id)
    favorite.destroy if favorite
  end

  def follows
    @parents = Category.all.order("id ASC").limit(2)
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    @parents = Category.all.order("id ASC").limit(2)
    user = User.find(params[:id])
    @users = user.followers
  end

  def bookmarks
    user = User.find(params[:id])
    @users = user.bookmarks.ids
    @bookmark = @users
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :avatar)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/bookmarks.html.haml
%h1 お気に入り一覧
- @users.each do |user|
  = image_tag user.avatar.to_s, class: "content__tops__user__icon"
  = link_to user.name, user_path(user.id), class: "content__follow__list__show"

app/views/users/edit.html.haml
#bg-video= video_tag "test.mp4", autoplay: true, muted: true, preload: true, loop: true, playsinline: true
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", root_path, class: 'btn'
      = link_to "マイページへ戻る", user_path(@user.id), class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :Email
          .field-input
            = f.email_field :email
        .field
          .field-label
            profile image
            .avatar
              - if @user.avatar.present?
                = image_tag @user.avatar.to_s, id: "user_prev", width: "100", height: "100"
              - else
                = image_tag asset_path("default.jpg"), id: "user_prev"
              = f.file_field :avatar, class: 'main-bottom__text__image__file', id: "user_img"
              = f.label :avatar, class: 'main-bottom__text__image', for: "user_img" do
                = icon('fas', 'image', class: 'image-icon')
  
        .actions
          = f.submit "Update", class: 'btn'


      

app/views/users/followers.html.haml
.wrapper
  = render "posts/header"
  .content
    .content__topics
      .content__follow
        %h1 follows
        .list
          - @users.each do |user|
            %p
              = image_tag user.avatar.to_s, class: "content__tops__user__icon"
              = link_to user.name, user_path(user.id), class: "content__follow__list__show"
              - if current_user != user
                - if user.followed_by?(current_user)
                  = link_to "フォロー中", user_relationships_path(user.id), method: :delete, class: "followers__name", id: "followers__name"
                - else
                  = link_to "フォローする", user_relationships_path(user.id), method: :post, class: "followers__lists"

        %span
        = link_to "マイページへ戻る", user_path(current_user.id), class: "content__follow__list"
  
  = link_to "前のページへ戻る", :back, class: "search-footer__btn"

app/views/users/follows.html.haml
.wrapper
  = render "posts/header"
  .content
    .content__topics
      .content__follow
        %h1 follows
        .list
          - @users.each do |user|
            %p
              = image_tag user.avatar.to_s, class: "content__tops__user__icon"
              = link_to user.name, user_path(user.id), class: "content__follow__list__show"
              - if current_user != user
                - if user.followed_by?(current_user)
                  = link_to "フォロー中", user_relationships_path(user.id), method: :delete, class: "followers__name", id: "followers__name"
                - else
                  = link_to "フォローする", user_relationships_path(user.id), method: :post, class: "followers__lists"
              
        %span
        = link_to "マイページへ戻る", user_path(current_user.id), class: "content__follow__list"

  = link_to "前のページへ戻る", :back, class: "search-footer__btn"

app/views/users/index.html.haml
%h1 Users#index
%p Find me in app/views/users/index.html.erb
- @users.each do |user|
  %hr/
  %p
    %span email:
    = link_to user.email, user_path(user.id)
  / ここを追加
  - if current_user != user
    - if user.followed_by?(current_user)
      %p= link_to "フォロー済み", user_relationships_path(user.id), method: :delete
    - else
      %p= link_to "フォローする", user_relationships_path(user.id), method: :post
  / ここまで

%h1 ユーザー一覧
- @users.each do |user|
  //<a href="/users/<%= user.id %>"><%= user.email %></a>
  %hr
= link_to "ホームへ戻る", posts_path

app/views/users/show.html.haml
.wrapper
  = render "posts/header"
  .content
    .content__tops
      .content__tops__user
        - if signed_in?
          - if current_user.id == @posts.ids do
            = link_to edit_user_path(@posts.ids), class: "content__tops__user__name"
              = image_tag @user.avatar.to_s, class: "content__tops__user__name__icon"
            = link_to @name, root_path(@posts.ids), class: "content__tops__user__name"
          - else
            = image_tag @user.avatar.to_s, class: "content__tops__user__name__icon"
            = link_to @name, edit_user_path(current_user.id), class: "content__tops__user__name"
        - else
          = image_tag @user.avatar.to_s, class: "content__tops__user__name__icon"
          .content__tops__user__name
            = @name
    
        - if signed_in?
          .follow
            = link_to "フォロー", follows_user_path(@user.id), class: "content__tops__followings"
            %h5= @user.followings.count
            = link_to "フォロワー", followers_user_path(@user.id), class: "content__tops__followers"
            %h5= @user.followers.count
            - if current_user != @user
              - if @user.followed_by?(current_user)
                %p
                = link_to "フォロー中", user_relationships_path(@user.id), method: :delete, class: "followers__ok"
              - else
                %p
                = link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "followers__list"
        - else
          .follow
            .content__tops__followings フォロー
            %h5= @user.followings.count
            .content__tops__followers フォロワー
            %h5= @user.followers.count
           



    %h4.user-post
      = @name
      さんの投稿
      = @posts.count.to_s + "件"
            
    - if user_signed_in? && current_user.id == @user.id
      .menu-box--left
        %ul
          %li.menu-box--left__category
            = icon('fas', 'ellipsis-h')
            %ul.menu-box--left__parents
              %li.menu-box--left__parents__parent
                = link_to 'お気に入り', bookmarks_index_path
                %br
                = link_to 'アカウント編集', edit_user_path(current_user.id)        
    




    .content__topic
      .content__topic__lists--show
        - @posts.each do |post|
          = link_to post_path(post.id), class: "content__topic__lists a" do
            = image_tag asset_path(post.image.to_s)

  .footer
    .footer__title
      2020.02






    



    