config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'relationships/create'
  get 'relationships/destroy'
  get "following_posts" => "posts#following_posts"#追記
  get 'bookmarks/create'
  get 'bookmarks/destroy'
  get 'bookmarks/index'
  get 'items/index'
  root "posts#index"
  get '/post/hashtag/:name', to: "posts#hashtag"
  get '/post/:address', to: "posts#map"
  post '/posts/:post_id/favorites' => "favorites#create"
  delete '/posts/:post_id/favorites' => "favorites#destroy"
  
  resources :notifications, only: :index
  resources :categories, only: [:index, :new]

  resources :posts do
    resources :comments, only: [:create, :destroy]
    namespace :api do
      resources :comments, only: :index, defaults: { format: 'json' }
    end
    member do
      get :following, :followers, :users_posts#追記
      get :map
    end
    resource :bookmarks, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    
    collection do
      get 'search'
    end
  end

  
  resources :users do
    resources :notifications, only: :index
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # 追加
    get :followers, on: :member # 追加
    get :bookmarks, on: :member
  end
  

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  has_many :favorites, dependent: :destroy
  has_many :favorites_users, through: :favorites, source: :post

  has_many :bookmarks, dependent: :destroy

  has_and_belongs_to_many :hashtags

  geocoded_by :address
  after_validation :geocode

  has_many :notifications, dependent: :destroy

  mount_uploader :image, ImagesUploader

  validates :image, presence: true
  validates :text, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  def self.search(search)
    return Post.all unless search
    Post.where('text LIKE(?) OR address LIKE(?)', "%#{search}%", "%#{search}%")
  end

  #DBへのコミット直前に実施する
  after_create do
    post = Post.find_by(id: self.id)
    hashtags  = self.text.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      #ハッシュタグは先頭の'#'を外した上で保存
      tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
      post.hashtags << tag
    end
  end

  before_update do 
    post = Post.find_by(id: self.id)
    post.hashtags.clear
    hashtags = self.text.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
      post.hashtags << tag
    end
  end

  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'favorite'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'favorite'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_tweet, only: [:edit, :show, :map]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    @posts = Post.includes(:user).order("created_at DESC").page(params[:page]).per(18)
    @posts1 = Post.includes(:user).order("RAND()").limit(5).offset(1)
    @posts2 = Post.includes(:user).order("RAND()").limit(4).offset(6)
    @posts3 = Post.includes(:user).order("RAND()").limit(5).offset(10)
    @post = Post.new
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all
    end
    #ログインしている場合（フォローしている人の投稿のみ表示）
    if user_signed_in?
      @user = current_user
      @users = @user.followings
    else
      
    end
  end

  def new
    @topic = Post.new
    @post = Post.new
    @posts = Post.includes(:user).order("RAND()")
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to user_path(@post.user_id)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
  end

  def edit
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to user_path(current_user.id)
  end

  def show
    @topic = Post.find(params[:id])
    @comments = @post.comments.includes(:user)
    @posts = Post.includes(:user)
    @user = current_user
    @tag = Hashtag.find_by(hashname: params[:name])
    @comment    = Comment.new
    @post = Post.find(params[:id])
  end

  def search
    @posts = Post.search(params[:keyword])
    respond_to do |format|
      format.html
      format.json
    end
  end

  def following_posts
    @user = current_user
    @users = @user.followings.posts.order("created_at DESC").page(params[:page]).per(20)
  end

  def hashtag
    @user = current_user
    @tag = Hashtag.find_by(hashname: params[:name])
    @posts = @tag.posts.build
    @post  = @tag.posts.page(params[:page])
    @comment    = Comment.new
    @comments   = @posts.comments
  end

  def map
    @address = @post.address
    @posts = Post.where(address: @address)
  end
  
  private
  def post_params
    params.require(:post).permit(:image, :text, :address, :latitude, :longitude).merge(user_id: current_user.id)
  end

  def set_tweet
    @post = Post.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end


end

app/helpers/posts_helper.rb
module PostsHelper
  def render_with_hashtags(text)
    text.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/){|word| link_to word, "/post/hashtag/#{word.delete("#")}"}.html_safe
  end  
end

app/views/posts/_following_posts.html.haml
.follow-top
  - @users.each do |user|
    -# = user.name
    -# - @posts = Post.where(user_id: user.id).limit(30).order("created_at DESC")
    - if user.posts.present?
      .contents.row
        .name1
          = link_to post_path(user.posts.last.id) do
            = image_tag asset_path("#{user.posts.last.image.to_s}")
        .name2
          #{link_to user.name, user_path(user), method: :get}
        = simple_format render_with_hashtags(user.posts.last.text.slice(0...8) + " ..."), class: "name3"
        .name5
          %time(datetime="#{user.posts.last.created_at}")= time_ago_in_words(user.posts.last.created_at) + "前"

  .contents.row
    .name1
      = link_to post_path(current_user.posts.last.id) do
        = image_tag asset_path("#{current_user.posts.last.image.to_s}")
    .name2
      #{link_to current_user.name, user_path(current_user), method: :get}
    = simple_format render_with_hashtags(current_user.posts.last.text.slice(0...8) + " ..."), class: "name3"
    .name5
      %time(datetime="#{current_user.posts.last.created_at}")= time_ago_in_words(current_user.posts.last.created_at) + "前"

app/views/posts/_header.html.haml
.header
  .header__inner
    .header__inner--list
      .header__inner__logo
        = link_to "CAMP", root_path, class: "header__inner__logos"
      .header__inner__right
        - if user_signed_in?
          .header__inner__right__post
            = link_to new_post_path, class: "header__inner__right__post--btn" do
              = icon('fas', 'plus-circle')
              .header__inner__right__post--btn
                post
          .header__inner__right__search
            = link_to search_posts_path, class: "header__inner__right__search--btn" do
              = icon('fas', 'search')
              .header__inner__right__search--btn__name
                Search
          .header__inner__right__user
            = link_to user_path(current_user.id), class: "header__inner__right__user--btn" do
              = icon('fas', 'street-view')
              .header__inner__right__user--btn__name
                = current_user.name
          .header__inner__right__logout
            = link_to destroy_user_session_path, method: :delete, class: "header__inner__right__logout--btn" do
              = icon('fas', 'user')
              .header__inner__right__logout--btn__name
                Logout
        - else
          .header__inner__right__user
            = link_to new_user_registration_path, class: "header__inner__right__user--btn" do
              = icon('fas', 'user-plus')
              .header__inner__right__newuser--btn__name
                signup
          .header__inner__right__login
            = link_to new_user_session_path, class: "header__inner__right__login--btn" do
              = icon('fas', 'user')
              .header__inner__right__login--btn__name
                Login
          .header__inner__right__search
            = link_to search_posts_path, class: "header__inner__right__search--btn" do
              = icon('fas', 'search')
              .header__inner__right__search--btn__name
                Search
      #nav-drawer
        %input{ id:"nav-input", type:"checkbox", class:"nav-unshown" }
        %label{ id:"nav-open", for:"nav-input" }
          %span
        %label{ class:"nav-unshown", id:"nav-close", for:"nav-input" }
        #nav-content
          - if user_signed_in?
            .nav-content__post
              = link_to new_post_path, class: "nav-content__post--btn" do
                /= icon('fas', 'plus-circle')
                .nav-content__post--btn
                  %span.nav-btn New Post
            .nav-content__post
              = link_to search_posts_path, class: "nav-content__search--btn" do
                /= icon('fas', 'search')
                .nav-content__search--btn__name
                  %span.nav-btn Search
            .nav-content__post
              = link_to user_path(current_user.id), class: "nav-content__user--btn" do
                /= icon('fas', 'street-view')
                .nav-content__user--btn__name
                  %span.nav-btn= current_user.name
            .nav-content__post
              = link_to destroy_user_session_path, method: :delete, class: "nav-content__logout--btn" do
                /= icon('fas', 'user')
                .nav-content__logout--btn__name
                  %span.nav-btn Logout
          - else
            .nav-content__post
              = link_to new_user_registration_path, class: "nav-content__user--btn" do
                /= icon('fas', 'user-plus')
                .nav-content__newuser--btn__name
                  %span.nav-btn signup
            .nav-content__post
              = link_to new_user_session_path, class: "nav-content__login--btn" do
                /= icon('fas', 'user')
                .nav-content__login--btn__name
                  %span.nav-btn Login
            .nav-content__post
              = link_to search_posts_path, class: "nav-content__search--btn" do
                /= icon('fas', 'search')
                .nav-content__search--btn__name
                  %span.nav-btn Search


  %ul.gnav
    %li
      %a{href:""}ONLINE SHOP

      %ul.first
        %li
          - @parents.each do |parent|
            = link_to "#{parent.name}", categories_path(parent), class: "parent_category",id: "#{parent.id}"
          %ul
            %li.children_list
              - @parents.each do |parent|
                - parent.children.each do |child|
                  = link_to "#{child.name}", categories_path(child), class: "children_category",id: "#{child.id}"
              %ul
                %li.grand_children_list
                  - @parents.each do |parent|
                    - parent.children.each do |child|
                      - child.children.each do |grandchild|
                        = link_to "#{grandchild.name}", categories_path(grandchild), class: "grandchild_category",id: "#{grandchild.id}"
                                
    %li
      %a{href:""}
        NEWS
      %ul.first
        %li
          %a{href:""}
            Child1
          %ul
            %li
              %a{href:""}
                Grandchild1
              %ul
                %li
                  %a{href:""}
                    Greatgrandchild1
                %li
                  %a{href:""}
                    Greatgrandchild2
                %li
                  %a{href:""}
                    Greatgrandchild3
            %li
              %a{href:""}
                Grandchild2
              %ul
                %li
                  %a{href:""}
                    Greatgrandchild1
                %li
                  %a{href:""}
                    Greatgrandchild2
                %li
                  %a{href:""}
                    Greatgrandchild3
            %li
              %a{href:""}
                Grandchild3
            %li
              %a{href:""}
                Grandchild4
            %li
              %a{href:""}
                Grandchild5
    %li
      %a{href:""}
        location
      %ul.first
        %li
          %a{href:""}
            北海道
        %li
          %a{href:""}
            東北
        %li
          %a{href:""}
            東日本
        %li
          %a{href:""}
            西日本
          %ul
            %li
              %a{href:""}
                関西
              %ul
                %li
                  %a{href:""}
                    大阪
                %li
                  %a{href:""}
                    京都
                %li
                  %a{href:""}
                    兵庫
                %li
                  %a{href:""}
                    奈良
                %li
                  %a{href:""}
                    滋賀
                %li
                  %a{href:""}
                    和歌山
        %li
          %a{href:""}
            沖縄
          %ul
            %li
              %a{href:""}
                Grandchild1
              %ul
                %li
                  %a{href:""}
                    Greatgrandchild1
                %li
                  %a{href:""}
                    Greatgrandchild2
                %li
                  %a{href:""}
                    Greatgrandchild3
            %li
              %a{href:""}
                Grandchild2
            %li
              %a{href:""}
                Grandchild3
            %li
              %a{href:""}
                Grandchild4
            %li
              %a{href:""}
                Grandchild5
    %li
      %a{href:""}
        Gurume
      %ul.first
        %li
          %a{href:""}
            メスティン
        %li
          %a{href:""}
            ホットサンド
        %li
          %a{href:""}
            ダッチオーブン
        %li
          %a{href:""}
            スキレット
        %li
          %a{href:""}
            朝食
          
    %li
      %a{href:""}
        Menu5
      %ul.first
        %li
          %a{href:""}
            Child1
          %ul
            %li
              %a{href:""}
                Grandchild1
              %ul
                %li
                  %a{href:""}
                    Greatgrandchild1
                %li
                  %a{href:""}
                    Greatgrandchild2
                %li
                  %a{href:""}
                    Greatgrandchild3
            %li
              %a{href:""}
                Grandchild2
            %li
              %a{href:""}
                Grandchild3
            %li
              %a{href:""}
                Grandchild4
            %li
              %a{href:""}
                Grandchild5






 

app/views/posts/_main.html.haml
= render "header"

.content
  %ul.slider
    %li
      = image_tag asset_path('aa.jpg')
    %li
      = image_tag asset_path('aaa.jpg')

  - if user_signed_in?
    - if @user.followings.count == 0
      .content__top
        .content__top__nosign
          - @posts1.each_with_index do |post, i|
            = link_to post_path(post.id), data: { index: i += 1 } do
              = image_tag asset_path("#{post.image.to_s}")
        - if @posts[5].present?
          .content__top__nosign
            - @posts2.each_with_index do |post, i|
              = link_to post_path(post.id), data: { index: i += 6 } do
                = image_tag asset_path("#{post.image.to_s}")
        - if @posts[9].present?
          .content__top__nosign
            - @posts3.each_with_index do |post, i|
              = link_to post_path(post.id), data: { index: i += 10 } do
                = image_tag asset_path("#{post.image.to_s}")
    - else
      .content-bottom
        .content-bottom__name
          FOLLWER
      .content__topics
        .content__topics__list
          .content-bottom
            = render "following_posts"
  - else
    .content__top
      .content__top__nosign
        - @posts1.each_with_index do |post, i|
          = link_to post_path(post.id), data: { index: i += 1 } do
            = image_tag asset_path("#{post.image.to_s}")
      - if @posts[5].present?
        .content__top__nosign
          - @posts2.each_with_index do |post, i|
            = link_to post_path(post.id), data: { index: i += 6 } do
              = image_tag asset_path("#{post.image.to_s}")
      - if @posts[9].present?
        .content__top__nosign
          - @posts3.each_with_index do |post, i|
            = link_to post_path(post.id), data: { index: i += 10 } do
              = image_tag asset_path("#{post.image.to_s}")
        
  -if @post.image.to_s == 0
  -else
    .content-bottom
      .content-bottom__name
        LANKING
      .content-bottom__list
        - @all_ranks.each_with_index do |post, i|
          = link_to post_path(post.id), data: { index: i += 1 } do
            = image_tag asset_path("#{post.image.to_s}")


.footer
  © CAMP

app/views/posts/create.html.haml
.wrapper
  = render "header"
  .content
    .content__main
      %h2 投稿完了しました。
      %br
      = link_to '投稿一覧へ戻る', "/posts", style: 'padding: 10px',class: "content__main__btn"

app/views/posts/destroy.html.haml
.wrapper
  = render "header"
  .content-destroy
    .content__destroy__main
      %h2 削除完了しました。
      %br
      = link_to 'マイページへ戻る', user_path(current_user.id), style: 'padding: 10px',class: "content__main__btn__destroy"

app/views/posts/edit.html.haml
.wrapper
  = render "header"
  .content
    .content__main
      = form_with(model: @post, local: true) do |form|
        .image-list
          = image_tag asset_path(@post.image.to_s), width: "200", height: "200", class: "image-box"
          = form.file_field :image, id: "new-image"
          %label{for: "new-image", class: "edit-post"}
            %pre.fas.fa-camera
              %p.new-post__font
        .image-text
          = form.label :address, class: "new-label"
          = form.text_field :address, placeholder: " ex ) ○○キャンプ場", class: "content__main__text", id: "address"
          %input{for: "address", type: "button", value: "Search", onclick: "codeAddress()", class: "content__main__btn"}
            #map{style: "width:650px; height: 300px"}
          = form.label :text, class: "new-label"
          = form.text_area :text, rows: "10", class: "content__main__text", required: ""
          %br
          = form.submit "SEND", style: 'padding: 10px',class: "content__main__btn"

          = javascript_include_tag src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=#{Rails.application.credentials.google_map_api}&libraries=places&callback=initMap", async: true, defer: true

          :javascript
            let map
            let geocoder

            function initMap(){
              // geocoderを初期化
              geocoder = new google.maps.Geocoder()
              map = new google.maps.Map(document.getElementById('map'), {
              center: {lat: -34.397, lng: 150.644},
              zoom: 15
              });
            }

            function codeAddress(){
              // 入力を取得
              let inputAddress = document.getElementById('address').value;
              
              // geocodingしたあとmapを移動
              geocoder.geocode( { 'address': inputAddress}, function(results, status) {
                if (status == 'OK') {
              // map.setCenterで地図が移動
                  map.setCenter(results[0].geometry.location);

                  // google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
                  var marker = new google.maps.Marker({
                      map: map,
                      position: results[0].geometry.location
                  });
                } else {
                  alert('Geocode was not successful for the following reason: ' + status);
                }
              });
            }
    
  = link_to "前のページへ戻る", :back, class: "search-footer__btn"

app/views/posts/hashtag.html.haml
.wrapper
  = render "header"
  - provide(:text, @tag.hashname)
  .content
    .content__topss
      .content__hash 
        %h1
        ='#'
        =@tag.hashname
        .name
          .name_hash
            - @post.each do |post|
              = link_to post_path(post.id) do
                = image_tag(post.image.to_s) 
          .edit_hash
            #follow_form
              - if current_user.followed_by?(@user)
                = form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }, remote: true) do |f|
                  = f.submit "フォロー解除", class: "btn"
              - else
                = form_for(user_relationships_path(@user.id), remote: true) do |f|
                  %div
                    = hidden_field_tag :followed_id, @user.id
  .row
    = link_to "前のページへ戻る", :back, class: "search-footer__btn"
    .posted_content
      .col-md-8
        .picture_hash

app/views/posts/index.html.haml
.wrapper
  = render "main"

app/views/posts/map.html.haml
.wrapper
  = render "header"
  .content
    .content__topss
      .address-name= @post.address

      #map

        = javascript_include_tag src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=#{Rails.application.credentials.google_map_api}&libraries=places&callback=initMap", async: true, defer: true

        :javascript
          function initMap() {
            var test ={ lat: #{@post.latitude}, lng: #{@post.longitude} };
            var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15,
              center: test
            });
            var transitLayer = new google.maps.TransitLayer();
            transitLayer.setMap(map);

            var contentString = "住所：#{@post.address} ";
            var infowindow = new google.maps.InfoWindow({
              content: contentString
            });

            var marker = new google.maps.Marker({
              position:test,
              map: map,
              title: contentString
            });

            marker.addListener('click', function() {
              infowindow.open(map, marker);
            });
          }
      
      .map-posts
        - @posts.each do |p|
          = link_to post_path(p.id), class: "map-posts__image" do
            = image_tag asset_path(p.image.to_s)

  = link_to "前のページへ戻る", :back, class: "search-footer__btn"
  .footer
    © CAMP

app/views/posts/new.html.haml
.wrapper
  = render "header"
  .content
    .content__main
      
      = form_with(model: @post, local: true) do |form|
        .image-list
          - if @post.persisted?
            = image_tag asset_path(@post.image.to_s), width: "200", height: "200", class: "image-box", required: ""
          = form.file_field :image, id: "new-image", required: ""
          %label{for: "new-image", class: "new-post", required: ""}
            %pre.fas.fa-camera
              %p.new-post__font new post !
        .image-text
          = form.label :address, class: "new-label"
          = form.text_field :address, placeholder: " ex ) ○○キャンプ場", class: "content__main__text", id: "address"
          %input{type: "button", value: "Search", onclick: "codeAddress()", class: "content__main__btn"}
            .google-map#map{style: "width:650px; height: 300px"}
          = form.label :text, class: "new-label"
          = form.text_area :text, rows: "10", class: "content__main__text", required: ""
          %br
          = form.submit "SEND", style: 'padding: 10px',class: "content__main__btn"
        

          = javascript_include_tag src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=#{Rails.application.credentials.google_map_api}&libraries=places&callback=initMap", async: true, defer: true

          :javascript
            let map
            let geocoder

            function initMap(){
              // geocoderを初期化
              geocoder = new google.maps.Geocoder()

              map = new google.maps.Map(document.getElementById('map'), {
              center: {lat: -34.397, lng: 150.644},
              zoom: 15
              });
            }

            function codeAddress(){
              // 入力を取得
              let inputAddress = document.getElementById('address').value;

              // geocodingしたあとmapを移動
              geocoder.geocode( { 'address': inputAddress}, function(results, status) {
                if (status == 'OK') {
              // map.setCenterで地図が移動
                  map.setCenter(results[0].geometry.location);

                  // google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
                  var marker = new google.maps.Marker({
                      map: map,
                      position: results[0].geometry.location
                  });
                } else {
                  alert('Geocode was not successful for the following reason: ' + status);
                }
              });
            }




        
  = link_to "前のページへ戻る", :back, class: "search-footer__btn"
              

app/views/posts/search.html.haml
.wrapper
  .footer-top
    = form_with(url: search_posts_path, local: true, method: :get, class: "search__form") do |form|
      .footer-search
        = form.text_field :keyword, placeholder: "", class: "search__form__input"
        = form.submit "検索", class: "search__form__bt", id: "a"
        %label{for: "a"}
          .search__form__btn= icon('fas', 'search')




  .search__content
    .search__topics
      - @posts.each do |post|
        = link_to post_path(post.id), class: "content__topic__lists a" do
          = image_tag(post.image.to_s)
          
  .search-footer
    = link_to "トップへ戻る", root_path, class: "search-footer__btn"
    

app/views/posts/show.html.haml
.wrapper
  = render "header"
  .content
    .content__topss
      .content__topss__text
        = image_tag asset_path(@post.user.avatar), class: "cooment-avatar", id: "post-avatar"
        = link_to @post.user.name, user_path(@post.user.id), class: "content__topss__name"
        
        = render "favorites/favorite"
        - if user_signed_in?
          - if @post.bookmarked_by?(current_user) 
            / ログインしているユーザーがお気に入りしたかどうかで分岐
            %p.bookmark-list
              //お気に入り解除
              = link_to post_bookmarks_path(@post.id), method: :delete, id: 'bookmark-link' do
                = raw bookmark_icon(@post, current_user)
          - else
            %p.bookmark-list
              //お気に入り登録
              = link_to post_bookmarks_path(@post), method: :post, id: 'bookmark-link-to' do
                = raw bookmark_icon(@post, current_user)

      //ログイン中のユーザーであれば編集・削除ページ遷移可能
      - if user_signed_in? && current_user.id == @post.user.id
        .menu-box--left
          %ul
            %li.menu-box--left__category
              = icon('fas', 'ellipsis-h')
              %ul.menu-box--left__parents
                %li.menu-box--left__parents__parent
                  = link_to '編集', edit_post_path
                %li.menu-box--left__children
                  = link_to '削除', post_path, method: :delete
    .content__topicss
      .content__topicss__lists
        %a{"data-lightbox" => "group", :href => asset_path(@post.image.to_s), class: "prev-image"}
          %img{:src => asset_path(@post.image.to_s), :width => "300"}
        %h1= simple_format render_with_hashtags(@post.text)
        
        .list
          - if @post.address.present?
            = link_to @post.address, map_post_path(@post.id)
          %br
          %h2= @post.created_at.strftime("%Y/%m/%d %H:%M") 
        
        //コメント機能
        .show-comment
          %h2 <  コメント一覧  >
          .comment
            .comment__list
              - if @comments
                - @comments.each do |comment|
                  .com{data: {comment: {id: comment.id}}}
                    .comment__list__form
                      = image_tag asset_path(comment.user.avatar), class: "cooment-avatar"
                      = link_to comment.user.name, "/users/#{comment.user_id}"
                      %h4= comment.created_at.to_s(:datetime)
                    .comment__list__text
                      %h3= comment.text

          .show-footer
            - if current_user
              %h3 comment
              = form_with(model: [@post, @comment], local: true, id: "new_comment") do |form|
                = form.text_area :text, rows: "2", class: "comment__main"
                = form.submit "SEND", style: 'padding: 10px',class: "comment__bt", id: "comment-send"
                %label{for: "comment-send"}
                  .comment__btn= icon('fas', 'paper-plane')
                  
            - else
              .show-footer__list
                %p  コメントの投稿には
                = link_to "新規登録 / ログイン", new_user_registration_path
                %p  が必要です


    .show__topss
      %h2
        投稿一覧
      .show__content__topic
        - @posts.each do |post|
          = link_to post_path(post.id), class: "show__content__topic__image" do
            = image_tag asset_path(post.image.to_s)
    

    

    
      